name: Istanbul Uni Not Kontrol Agent

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir çalışır
  workflow_dispatch: # İstediğinde manuel başlatmak için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ← BU SATIRI EKLE
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Botu Çalıştır
        run: python main.py
        env:
          AKS_USER: ${{ secrets.AKS_USER }}
          AKS_PASS: ${{ secrets.AKS_PASS }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_ID: ${{ secrets.TG_ID }}

      - name: Hafıza Dosyasını Repoya Geri Kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add notlar_hafiza.txt
          git commit -m "🤖 Hafıza dosyası güncellendi [skip ci]" || echo "Değişiklik yok."
          git push
